### ISSUE TITLE
I am confused... Where is the LED? Is it a disabled item for 1.20.4.

### ISSUE THREAD

**Issue by makumaku1974** [MikiP98/HumilityAFM#6]
I've been trying to figure it out how to find the LED lights since it looks cool.

Not a Bug Report but a question.

**Comment by MikiP98** [comment]
Hi, 
Sorry for late response :)
After talking to my friends, we decided that LEDs look great but aren’t vanilla enough to be on by default.
**To see the LED in your game you will need to enable them in the config.**

To access the config in game, after clicking Escape or in the main menu you should click “Mods” tab, there search for “Humility” and click on the icon of the mod. 
Now you should see some config options including enabling LEDs.

Alternatively you can open the folder your game is installed, find folder “config”, find Humility JSON and change the setting by hand.

**In both cases remember to save the config!**

**Unfortunately the other mod that allows LEDs to actually emit coloured light (Ak. Blue LED dyeing nearby block bluish colour) named “Shimmer” is only available in 1.20.1 with 1.20.2 version on the horizon :(**
So in other versions than 1.20.1 (and soon 1.20.2) they can only be uses as a blending in, unobtrusive light source :(

Hope that helps!
Its nice to see that people are actually interested in the mod!
Thanks for the question and have a nice day!

**Comment by makumaku1974** [comment]
It's a perfect mod. Just hoping for shimmer to update to 1.20.4.
